### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elifoster** [elifoster/ModUpdater#1]
- [x] Parse configuration JSON for relevant information
- [x] Upload to CurseForge
- [x] Create announcement tweet on account given in configuration JSON
- [x] Update wiki changelog page and mod page with version and changelog provided by the JSON
- [ ] Attractive GUI (Here's a nice color pallet: http://paletton.com/#uid=52m1d1kl7v-aBPkguEzpOsIsSmskl7tSbrKYgO-CpNrmsslAkl7tSbrKYgO-CpNrmsslA)
  - Preferably in CSS and HTML

Example JSON now available in the repo

Storing passwords in the JSON will not happen for safety reasons. Instead, the user will simply need to supply the passwords in the console. Or, if I eventually make a GUI for this, which would be very simple, in a text field.
